# Generated by Django 3.0.2 on 2020-02-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
