# Generated by Django 3.0.2 on 2020-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
