# Generated by Django 3.0.2 on 2020-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares_count',
            field=models.IntegerField(default=0, verbose_name='Number of Shares to Purchase'),
        ),
    ]
