# Generated by Django 3.0.2 on 2020-07-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cacheTime', models.DateTimeField()),
                ('marketTime', models.TimeField()),
                ('openPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hinhPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lowPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'CachedStockData',
                'verbose_name_plural': 'CachedStockData',
            },
        ),
    ]
