# Generated by Django 3.0.2 on 2020-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0002_auto_20200224_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_key',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
