# Generated by Django 3.0.2 on 2020-07-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0003_cachedstockdata_companycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedstockdata',
            name='companyCode',
            field=models.CharField(max_length=50, verbose_name='Code'),
        ),
    ]
