# Generated by Django 3.0.2 on 2020-02-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0003_auto_20200225_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='', max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_key',
            field=models.CharField(default='', max_length=50, verbose_name='Key'),
        ),
    ]
