# Generated by Django 3.0.2 on 2020-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0004_auto_20200225_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Balance Amount'),
        ),
    ]
