# Generated by Django 3.0.2 on 2020-07-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0004_auto_20200718_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedstockdata',
            old_name='hinhPrice',
            new_name='highPrice',
        ),
    ]
