# Generated by Django 3.0.2 on 2020-02-21 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0004_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='_customuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares_count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeLoader.Company')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_count', models.IntegerField()),
                ('shares_sale', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeLoader.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeLoader.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='watch_list',
            field=models.ManyToManyField(related_name='is_interested_in', to='homeLoader.Company'),
        ),
    ]
