# Generated by Django 3.0.2 on 2020-07-19 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeLoader', '0005_auto_20200718_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeLoader.Shares')),
            ],
            options={
                'verbose_name': 'Wish List',
                'verbose_name_plural': 'Wish Lists',
            },
        ),
    ]
